FROM   golang:1.24-alpine  AS builder 

WORKDIR   /app  

RUN apk add --no-cache gcc musl-dev

COPY     go.mod go.sum ./ 
RUN      go mod download 

COPY     .   .  

#Enable CGO for sqlite
ENV     CGO_ENABLED=1
RUN     go build -o api ./cmd/api 


FROM alpine:3.20

WORKDIR   /app 

RUN apk add --no-cache sqlite-libs

COPY --from=builder /app/api .

EXPOSE   8080 
EXPOSE   2113 

CMD    ["./api"]