FROM  golang:1.24-alpine  AS builder 

WORKDIR    /app  

RUN apk add --no-cache gcc musl-dev

COPY    go.mod go.sum  ./ 
RUN    go mod download  

COPY    . .   

ENV  CGO_ENABLED=1

RUN    go build -o watcher ./cmd/watcher 


FROM alpine:3.20

WORKDIR /app 

RUN apk add --no-cache sqlite-libs 

COPY  --from=builder /app/watcher .

EXPOSE   2112 

CMD ["./watcher"]

